# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# This policy allows Chainguard employees to access private GitHub repositories
# using `chainctl auth octo-sts`, in order to generate short-lived, tightly-scoped
# GitHub access tokens when building packages locally.

issuer: https://accounts.google.com

subject_pattern: .*
claim_pattern:
  email_verified: "true"
  email: .*@chainguard.dev

permissions:
  contents: read

repositories:
  - ecosystems-avro
  - ecosystems-cassandra
  - ecosystems-elasticsearch
  - ecosystems-grpc-java
  - ecosystems-hadoop
  - ecosystems-hive
  - ecosystems-kafka
  - ecosystems-libcheck
  - ecosystems-neo4j
  - ecosystems-spark
  - iamguarded-charts
  - iamguarded-containers
  - iamguarded-tools
  - zulu-jdk21u
