issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: insights-publisher-sa@prod-images-c6e5.iam.gserviceaccount.com
subject: "101826719708554282120"

permissions:
  actions: read
  contents: read
  checks: read
  issues: read
  pull_requests: read

repositories:
  - enterprise-packages
  - enterprise-advisories
  - advisories
