issuer: https://accounts.google.com
# neko77@neko77.iam.gserviceaccount.com
subject: "113809027484440661352"
permissions:
  discussions: read
  email: read
  issues: read
  members: read
  pull_requests: read
  repository_projects: read
  statuses: read
# This operates across the entire organization.
repositories:
